const listaTrabajadores = [
    {
        cet : "30067",
        id : "A01734836",
        nombre : "Jorge Leonardo Garcia Reynoso",
        edad : 20,
        antiguedad : 3,
        estructura3 : "Por ahi",
        estructura4 : "estructura4",
        estructura5 : "estructura5",
        direccion : "Mi casita :)",
        puesto: "Desarrollo de Front End",
        pccat: "00000"
    },
    {
        cet : "30067",
        id : "A0987987",
        nombre : "Jorge Leonardo Garcia Reynoso",
        edad : 20,
        antiguedad : 3,
        estructura3 : "Por ahi",
        estructura4 : "estructura4",
        estructura5 : "estructura5",
        direccion : "Mi casita :)",
        puesto: "Desarrollo de Front End",
        pccat: "00000"
    },
    {
        cet : "30067",
        id : "A019873407",
        nombre : "Jorge Leonardo Garcia Reynoso",
        edad : 20,
        antiguedad : 3,
        estructura3 : "Por ahi",
        estructura4 : "estructura4",
        estructura5 : "estructura5",
        direccion : "Mi casita :)",
        puesto: "Desarrollo de Front End",
        pccat: "00000"
    },
    {
        cet : "30067",
        id : "A81347934",
        nombre : "Jorge Leonardo Garcia Reynoso",
        edad : 20,
        antiguedad : 3,
        estructura3 : "Por ahi",
        estructura4 : "estructura4",
        estructura5 : "estructura5",
        direccion : "Mi casita :)",
        puesto: "Desarrollo de Front End",
        pccat: "00000"
    },
    {
        cet : "30067",
        id : "A01823742",
        nombre : "Jorge Leonardo Garcia Reynoso",
        edad : 20,
        antiguedad : 3,
        estructura3 : "Por ahi",
        estructura4 : "estructura4",
        estructura5 : "estructura5",
        direccion : "Mi casita :)",
        puesto: "Desarrollo de Front End",
        pccat: "00000"
    },
    {
        cet : "30067",
        id : "A0912374",
        nombre : "Jorge Leonardo Garcia Reynoso",
        edad : 20,
        antiguedad : 3,
        estructura3 : "Por ahi",
        estructura4 : "estructura4",
        estructura5 : "estructura5",
        direccion : "Mi casita :)",
        puesto: "Desarrollo de Front End",
        pccat: "00000"
    },
    {
        cet : "30067",
        id : "A8383745",
        nombre : "Jorge Leonardo Garcia Reynoso",
        edad : 20,
        antiguedad : 3,
        estructura3 : "Por ahi",
        estructura4 : "estructura4",
        estructura5 : "estructura5",
        direccion : "Mi casita :)",
        puesto: "Desarrollo de Front End",
        pccat: "00000"
    },
    {
        cet : "30067",
        id : "A12345678",
        nombre : "Jorge Leonardo Garcia Reynoso",
        edad : 20,
        antiguedad : 3,
        area : "Por ahi",
        direccion : "Mi casita :)",
        puesto: "Desarrollo de Front End",
        pccat: "00000"
    },
    {
        cet : "30067",
        id : "A87342933",
        nombre : "Jorge Leonardo Garcia Reynoso",
        edad : 20,
        antiguedad : 3,
        area : "Por ahi",
        direccion : "Mi casita :)",
        puesto: "Desarrollo de Front End",
        pccat: "00000"
    },
    {
        cet : "30067",
        id : "A67823146",
        nombre : "Jorge Leonardo Garcia Reynoso",
        edad : 20,
        antiguedad : 3,
        estructura3 : "Por ahi",
        estructura4 : "estructura4",
        estructura5 : "estructura5",
        direccion : "Mi casita :)",
        puesto: "Desarrollo de Front End",
        pccat: "00000"
    },
    {
        cet : "30067",
        id : "A293847938",
        nombre : "Jorge Leonardo Garcia Reynoso",
        edad : 20,
        antiguedad : 3,
        estructura3 : "Por ahi",
        estructura4 : "estructura4",
        estructura5 : "estructura5",
        direccion : "Mi casita :)",
        puesto: "Desarrollo de Front End",
        pccat: "00000"
    }
];

export default listaTrabajadores;